### ISSUE TITLE
Exported PDF Styling doesn't match preview

### ISSUE THREAD

**Issue by dcrockwell** [tylingsoft/markdown-plus#83] opened 2017-01-20 22:12 UTC
Horizontal rules are invisible. Background colors for graph line text is gone.

**Comment by tylerlong** [comment] 2017-01-21 04:37
Please specify OS version and app version.

**Comment by dcrockwell** [comment] 2017-01-21 04:38
MacOS Sierra (10.12)
Markdown Plus Version 2.2.0 (26)

**Comment by tylerlong** [comment] 2017-01-21 04:51
I am unable to reproduce the issue you mentioned. Could you please help me?

![image](https://cloud.githubusercontent.com/assets/733544/22172032/365d97a2-dfd8-11e6-8910-415445bbab26.png)

**Comment by dcrockwell** [comment] 2017-01-21 04:57
Here's a screenshot of the PDF viewed via `Preview` in OSX on the left side, and Markdown Plus on the right.

![screen shot 2017-01-20 at 9 56 33 pm](https://cloud.githubusercontent.com/assets/53482/22172071/68b2c7b8-df5b-11e6-8561-9e3e63c76421.png)

**Comment by dcrockwell** [comment] 2017-01-21 04:58
I was wrong about the text labels, they're just a much lighter color I mistook for white.

(except maybe the ones on the dotted light under participations)

**Comment by dcrockwell** [comment] 2017-01-21 05:00
Here's a screenshot of the code to show that the proper `---` is being used for HR.

![screen shot 2017-01-20 at 10 00 16 pm](https://cloud.githubusercontent.com/assets/53482/22172094/d92f1a96-df5b-11e6-88e6-9d2554ceb737.png)

**Comment by tylerlong** [comment] 2017-01-21 05:26
Not sure why the horizontal rules are invisible in your screenshot. In my screenshot, It is visible.

I think as long as we figured out the root cause for horizontal rules invisible issue, we can also fix the graph line background color issue.

But first and foremost, I need to reproduce it.

Could you please try something simpler as shown in my screenshot and post the result here?

**Comment by tylerlong** [comment] 2017-01-21 05:30
I guess it has something to do with default printing settings of your OS:

![image](https://cloud.githubusercontent.com/assets/733544/22172294/b7dec6c0-dfdd-11e6-9aad-4c8cd52c31c3.png)

Could you please make sure that by default your OS has this option enabled?

**Comment by dcrockwell** [comment] 2017-01-21 05:41
I think it's the background graphics, but I can only enable it in other programs. When i go to File -> Print in Markdown Plus, I get a crash:

![screen shot 2017-01-20 at 10 39 49 pm](https://cloud.githubusercontent.com/assets/53482/22172353/6402c064-df61-11e6-86f5-8f152ead225d.png)

If I go to the print icon at the top toolbar, I don't see a way to enable background graphics from there:

![screen shot 2017-01-20 at 10 40 49 pm](https://cloud.githubusercontent.com/assets/53482/22172361/855a9110-df61-11e6-88cf-e4db7e0e49e3.png)

**Comment by tylerlong** [comment] 2017-01-21 15:53
The print dialog is system wide. You can enable it somewhere else. For example in your chrome browser print cmd - p to bring it up.

**Comment by tylerlong** [comment] 2017-01-22 01:23
I am not sure how to change your system-wide printing settings. But I do know a temporary workaround for the issue:

- When you want to create a pdf, launch chrome browser and navigate to http://mdp.tylingsoft.com/
- Copy and paste your markdown there
- <kbd>cmd - p</kbd> to bring up the printing preview dialog
- Change destination to `Save as PDF`
- Enable `Background Graphics
- Save the pdf

![image](https://cloud.githubusercontent.com/assets/733544/22179102/9f52f3ea-e084-11e6-976f-d86bb15f8242.png)

![image](https://cloud.githubusercontent.com/assets/733544/22179110/c0b5bc52-e084-11e6-94f1-67c89ccadc7d.png)


I will try to figure our a permanent solution soon. Please use the workaround for now.

**Comment by tylerlong** [comment] 2017-04-10 02:10
Fixed in latest version. 

Feel free to reopen if you still have issues.

**Closed as completed by tylerlong** 2017-04-10 02:10 UTC
